language: php
php:
- 7.4
jobs:
  include:
  - php: 7.4
    env: WP_TRAVISCI=travis:phpunit
  allow_failures:
  - php: 7.4
script: php index.php
deploy:
  provider: heroku
  app: test-php-vlad-1
  api_key:
    secure: JWFzlba/DzKkKTcHFpgSo5Yh7j4jyJfKo7P7/hLNPDWQ/I198jvZsoUYVYraYGvxv28S4zJat1fGh1Sh2d3JsJZpIsBFDs5WMkYF/x3GP46sWjQcE4YjRpktQTBHz3ibjz9feNTwbo/DGfUPJJgdkwSzCYu8TwYNE7z0qCjWt1ciWokjqMqkQ525CfZ5sLOYFVYRpaxJIJn2X5dH+EUKTJhg5k1ZyCCIWZhsRvfU088cVQUwDGJnJQRm1TWEQK4TkHRQNnvYRc3R1tNsB0jgKz3W9IOjR/vAO86KyW0pQFoukd5aEMOjXPwvz8iGkA2unndrvnEmT9F9dxk6TCm5Jnxvnl9M+o2hN2ZT6ROCAcLgjvW1zzDF0OObbreAOaiHqEUPslHY19QMmn4QxvaiXHn9eCxZe7SzjJkiP2b57yQtlxHUHk2jceLF86Yn/xJh38ZSwOZsbQJph/5nQoaZLk8asEV3hZCcwQKwtQUVyBrapDAu8aXNTWgKGw8y3D5uZ/m4YxanDMWptGGhomvsca3dO49OZpmwv0zCxyeod9cdpIx5NVvETn0szGQHYpZn3AW+o1h6jRnwkcVWQTBOX2pkvgARtwuTulbD1ou7tnURW6tX13/X9O6cgnW2VTkuVjFPc0XGBe764QgaV0J/TLIgvFGYYO9MTOUjtiKnvbc=
