language: php
php:
- 7.4
jobs:
  include:
  - php: 7.4
    env: WP_TRAVISCI=travis:phpunit
  allow_failures:
  - php: 7.4
script: php index.php  
  

deploy:
  provider: heroku
  app: test-php-vlad-1
  api_key:
    secure: gMRkGb1oPcukth5BA9y5olKUUEAoqDy/z7XtiVQmI6T5jRaMAxAjNR0ukhodhFdTfRaEubyN6wPU7chxKSqHPdATAdtATXCJfcJ3kANIVF8I66j3yrwdYC5xiOSoBnbBQKV97PJxUSWpLpje3oJLqVNaiLS6X84ZA5/arKWWykyO/+6awrEXvNU2TXcCJYIRllRkdKyyWfL+efPap5tPjBUAnBBcGq4/nqa8PMfhmBEFY6RfXMqSFWC2EIZ7zVKUQtxa8XLERJk4Hx9Cjv45vRTXLiTsgfJUvj8WVB5uXL6fGWkXpKr4MVZS2n6eZjZQbXCHHcTcpp5eubVS5WnAltXYomu2SeVbHSzSd9i8mxBdXWuILpB1K9Hzk+uQ/AwA9Gk1J7vAbU/xugiPOG9HMb31nzeDRX9G8/c9AGxEPZYkcAumR/pIt+ERSdF5IClmU5KTazgeG01aha0pjim365PscpdC1zYyteEcsS1v9Mc69PFxRnPIRK4qIcKBhXVz2Tl0KrlnkP6/b+vi0shkXgbzPqF6hyGSDHEOdAAePPlyMG3o1INqP6K2KcgKE8UQrMLP50CO6NoT2Myyhi5DxNTBloiBtSzMg6jN4SIGC1/uG4fd5SPbQ9jB4pm6ApCnGNKv5IlcppxqhVomK6sHgyA0VxIrOjhVJIeA5COZKmk=   