language: php
php:
- 7.4
jobs:
  include:
  - php: 7.4
    env: WP_TRAVISCI=travis:phpunit
  allow_failures:
  - php: 7.4
script: php index.php
deploy:
  provider: heroku
  app: test-php-vlad-1
  api_key:
    secure: inufGqCyuFr6LFPyNdZv8XQSlJmbwnRmfVEl7cWqH2Ua+dHBB2bQcJHVKgt4YHvyMtKXCArp1PYRKCuPGNBKAmH7JVAM/tqDo6NhV4ke4g0Cw9nL0qrQ+UxcuOMwS3jC3htyKcsNYgjvkvS09osPx7OR6h0tnH5piWg9oN3zYvk3KD792mxYsePbN4kmWZbQwT/13X5uyO5ex7RIy92LFlz4i6tQez5zqxXKkg3C+DzTzUvey8I7iW5jPnMKub6JwurJ+ksq+cxUNGbOk1fUMv7tIbIopLlY/4mHFAzgaWyuj3Se+C06K6x+D9A0QPiYMtIkGc5pX9N7/BWGaw1njOjbafjXQfTuGdMMCBIHrj/ET2XDAwYllF+LQgpp+p5f7zanfNAxWHJUQayiD5chmdsOw3LugbVTYagiNrdsoNZi0zQopc/7n5Mdhbxa7iVzfBI4M0rRLvIAELYABRYpQRXV0eF7y+RDTkDfOycPsa1m+21iZFgvWs2jDEaRbzy8I1o1W9382REyjKkmiPvhaFlKTNWG8le/wmgwj+BC6cTvkPnwzwsa1hQ45T5uDtAIjfXoOENf+ovHlIu1yJJHokUqJr3+4zbKlUZGHCnA/05JijOkXHfZMYceg8PZ/oSHOXnFSIuqifjmhP4cxVjZZ6MnbRcminCgMHtB6G1X9hI=
