language: php
php:
- 7.4
jobs:
  include:
  - php: 7.4
    env: WP_TRAVISCI=travis:phpunit
  allow_failures:
  - php: 7.4
script: php index.php
deploy:
  provider: heroku
  api_key: 024a6233-b2d4-4818-8224-d4ff91f1af9f
  app: test-php-vlad-1
  on:
    repo: vladgaus/test-cicd
  skip_cleanup: 'true'
