language: php
php:
- 7.4
jobs:
  include:
  - php: 7.4
    env: KEY=VALUE
  allow_failures:
  - php: 7.4
    env: KEY=VALUE

deploy:
  provider: heroku
  app: test-php-vlad-1
  api_key: "e96833b7-69cb-4fb6-bfd3-653dccc91e79"    